#!/usr/bin/env bash

set -u
set -e

vms=`VBoxManage list vms | grep ^\"vyos-ami-build | awk '{print $2}'`

for machine in $vms; do
    echo "Unregistering $machine"
    echo -n "Hit enter to unregister this VM: " 
    VBoxManage list vms | fgrep $machine
    read dummy
    set +e
    VBoxManage showvminfo $machine | grep ^State | fgrep running
    if [ $? -eq 0 ]; then
        VBoxManage controlvm $machine poweroff
        # Wait for the VM to shut down
        while true; do
            VBoxManage showvminfo $machine | grep ^State | fgrep 'powered off'
            if [ $? -eq 0 ]; then
                break
            fi
        done
    fi
    set -e
    echo "Unregistering..."
    VBoxManage unregistervm --delete $machine
done
