#!/usr/bin/env bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 <ami id>"
    exit 1
fi

ami_id=$1

source_region=ap-southeast-1

for region in `ec2-describe-regions | awk '{print $2}' | fgrep -v $source_region`; do
    echo -n "$region: "
    ec2-copy-image --region $region --source-region $source_region --source-ami-id $ami_id
done
